name = "gymlog-worker"
main = "worker/index.ts"
compatibility_date = "2024-06-20"
workers_dev = true

[assets]
directory = "src"
binding = "ASSETS"

[[r2_buckets]]
binding = "OBSIDIAN"
bucket_name = "obsidian"
preview_bucket_name = "obsidian"
